apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-app
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: ghcr.io/joarfj/argocd-demo-backend:1fd98a601581e1e7183366c7d51dee8288a33634
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080