apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: ghcr.io/joarfj/argocd-demo-backend:91839a7c237d8fd9f345f8af4cc9c0a5e963380e
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080