apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-app
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: ghcr.io/joarfj/argocd-demo-backend:80938c7be6f134b5dac27ef1bf08723c4fc5ef80
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080