apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: ghcr.io/joarfj/argocd-demo-backend:c8579c5c12a0d0dab4a967fceed8b5e18af6bd93
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080