apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: ghcr.io/joarfj/argocd-demo-frontend:082a9393c3c523443eb4e9e6e22f9cecd592d2be # Placeholder, will be updated by CI/CD
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
