apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-app
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: ghcr.io/joarfj/argocd-demo-frontend:69dea12cff9853ac97006d49c846167893de9fd8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
