apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-app
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: ghcr.io/joarfj/argocd-demo-frontend:6cf0bcb5c5340d722ec7408cc696e3f5a10003a8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
