apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: ghcr.io/joarfj/argocd-demo-frontend:91839a7c237d8fd9f345f8af4cc9c0a5e963380e
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
