name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert repository name to lowercase
        id: repo_lowercase
        run: echo "name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower__]')" >> $GITHUB_OUTPUT

      - name: Build and push Backend Docker image
        id: build-and-push-backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.repo_lowercase.outputs.name }}-backend:${{ github.sha }}

      - name: Build and push Frontend Docker image
        id: build-and-push-frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.repo_lowercase.outputs.name }}-frontend:${{ github.sha }}

      - name: Update Kubernetes manifests
        run: |
          sed -i "s|image: ghcr.io/joarfj/argocd-demo-backend:latest|image: ghcr.io/${{ steps.repo_lowercase.outputs.name }}-backend:${{ github.sha }}|" k8s/backend-deployment.yaml
          sed -i "s|image: ghcr.io/joarfj/argocd-demo-frontend:latest|image: ghcr.io/${{ steps.repo_lowercase.outputs.name }}-frontend:${{ github.sha }}|" k8s/frontend-deployment.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add k8s/backend-deployment.yaml k8s/frontend-deployment.yaml
          git commit -m "Update backend image to ${{ github.sha }} and frontend image to ${{ github.sha }}"
          git push
